###
# Configures the web application, and collects static assets
#
---

- name: run the django syncdb command
  django_manage: app_path={{app_code_dir}}
    command="syncdb"
    virtualenv={{app_env_dir}}
    settings={{django_settings}}
  environment: app_env_vars
  sudo: yes
  sudo_user: "{{app_name}}"
  tags: django

- name: run the django migrate command
  django_manage: app_path={{app_code_dir}}
    command="migrate"
    virtualenv={{app_env_dir}}
    settings={{django_settings}}
  environment: app_env_vars
  sudo: yes
  sudo_user: "{{app_name}}"
  tags: django

- name: run the django collectstatic command
  django_manage: app_path={{app_code_dir}}
    command="collectstatic"
    virtualenv={{app_env_dir}}
    settings={{django_settings}}
  environment: app_env_vars
  sudo: yes
  sudo_user: "{{app_name}}"
  tags:
    - django
    - collectstatic

- name: run tests
  django_manage: app_path={{app_code_dir}}
    command="test registration"
    virtualenv={{app_env_dir}}
    settings={{django_settings}}
  environment: app_env_vars
  sudo_user: "{{app_name}}"
  when: run_tests
  tags:
    - django
    - tests
