###
# Configuration for Nginx web server
---

- name: write nginx configuration without SSL
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/{{app_name}}.conf
  sudo: yes
  when: not use_ssl
  notify:
    - restart nginx
  tags:
    - nginx

- name: write nginx configuration with SSL
  template: src=nginx.ssl.conf.j2 dest=/etc/nginx/sites-enabled/{{app_name}}.conf
  sudo: yes
  when: use_ssl
  notify:
    - restart nginx
  tags:
    - nginx

- name: check if nginx has default symbolic linked website file
  stat: path=/etc/nginx/sites-enabled/default
  register: nginx_default_file
  tags:
    - nginx

- name: delete default symbolic linked website on nginx
  command: rm /etc/nginx/sites-enabled/default
  sudo: yes
  when: nginx_default_file.stat.exists
  notify:
    - restart nginx
  tags:
    - nginx
