###
# updates the APT package cache and install packages necessary for web
# servers
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure web server packages are installed
  apt: name={{item}} state=latest
  sudo: yes
  with_items:
    - binutils
    - build-essential
    - git
    - libncurses5-dev
    - libjpeg-dev
    - memcached
    - mercurial
    - nginx
    - python-dev
    - python-pip
    - supervisor
    # - gdal-bin
    # - libproj-dev

- name: install app-specific packages
  apt: name={{item}} state=latest
  sudo: yes
  with_items: base_app_apt_packages

- name: install dev packages
  apt: name={{item}} state=latest
  sudo: yes
  with_items: dev_app_apt_packages
  when: install_dev_packages

- name: install test packages
  apt: name={{item}} state=latest
  sudo: yes
  with_items: test_app_apt_packages
  when: install_test_packages

- name: global pip installs
  pip: name={{item}}
  with_items:
    virtualenv
  sudo: yes
